const $=id=>document.getElementById(id);let clients=[],settings={},me=null;
async function req(u,o={}){let r=await fetch(u,{credentials:'include',...o});let d=await r.json();if(!r.ok)throw Error(d.msg||'خطا');return d}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));let t={dashboard:'داشبورد',clients:'کلاینت‌ها',configs:'کانفیگ‌ها و Subscription',settings:'تنظیمات',account:'حساب من',admin:'مدیریت ادمین'}[id];$('title').textContent=t;if(id==='configs')renderConfigs()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>openTab(x.dataset.tab));
function updateProtocolFields(){const p=$('protocol')?.value; const f=$('dnsField'); if(f){f.classList.add('hidden');f.innerHTML=''} const note=$('createMsg'); if(note&&p==='dns') note.textContent='برای این کاربر یک DNS اختصاصی DoH با حجم و اعتبار جداگانه ساخته می‌شود.'; else if(note && note.textContent.includes('DNS پیش‌فرض')) note.textContent=''}
$('protocol')?.addEventListener('change',updateProtocolFields);
window.addEventListener('DOMContentLoaded',updateProtocolFields);
async function login(){try{let d=await req('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});if(!d.success)throw Error(d.msg);showApp()}catch(e){$('loginMsg').textContent=e.message}}
let liveRefreshTimer=null;function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');refresh();loadSettings();loadMe();if(!liveRefreshTimer)liveRefreshTimer=setInterval(refresh,1000)}
async function refresh(){try{let d=await req('/api/clients');clients=d.clients;$('count').textContent=clients.length;$('active').textContent=clients.filter(x=>x.enabled&&!expired(x)).length;$('expired').textContent=clients.filter(expired).length;renderClients();renderConfigs();updateDash()}catch(e){if(e.message.includes('ورود'))location.reload()}}
function expired(c){return c.expiryAt && c.expiryAt*1000<Date.now()}
async function loadMe(){try{let d=await req('/api/me');me=d.user;if(me){$('accUser').value=me.username;$('adminNav').classList.toggle('hidden',me.role!=='admin');if(me.role==='admin')loadUsers()}}catch{}}
function fmtUsed(n){n=Number(n||0);const u=['B','KB','MB','GB','TB'];let i=0,x=n;while(x>=1024&&i<u.length-1){x/=1024;i++}return (i>=3?x.toFixed(2):Math.round(x*100)/100)+' '+u[i]}
function renderClients(){$('clientsList').innerHTML=clients.length?clients.map(c=>{const used=Number(c.used||0),total=Number(c.totalBytes||0),pct=total?Math.min(100,used/total*100):0;const cls=pct>=95?'danger':pct>=80?'warn':'';return `<div class="client-row"><div class="client-meta"><b>${esc(c.name)}</b><small>${c.protocol.toUpperCase()} · ${c.gb} GB · ${c.days} روز · ${expired(c)?'منقضی':(c.online?'آنلاین':'فعال')}</small></div><div class="usage"><div class="usage-top"><span>مصرف</span><strong>${esc(c.usedText||fmtUsed(used))} / ${esc(c.totalText||fmtUsed(total))} · ${pct.toFixed(1)}%</strong></div><div class="usage-bar"><div class="usage-fill ${cls}" style="width:${pct}%"></div></div></div><div class="row-actions"><button class="mini" onclick="copy('${enc(c.config)}')">کپی ${esc(c.protocol.toUpperCase())}</button><button class="mini" onclick="copy('${enc(c.subscription)}')">کپی Sub</button><button class="danger mini" onclick="del(${c.id})">حذف</button></div></div>`}).join(''):'<div class="empty">هنوز کلاینتی ساخته نشده است.</div>'}
function renderConfigs(){$('configList').innerHTML=clients.length?clients.map(c=>`<div class="config-card"><div class="config-top"><div><b>${esc(c.name)}</b><span class="tag">${esc(c.protocol.toUpperCase())} · ${expired(c)?'منقضی':'فعال'}</span></div><small>${c.gb} GB · تا ${new Date(c.expiryAt*1000).toLocaleDateString('fa-IR')}</small></div><label>کانفیگ ${esc(c.protocol.toUpperCase())}</label><div class="copybox"><code>${esc(c.config)}</code><button onclick="copy('${enc(c.config)}')">کپی</button></div>${c.protocol==='dns'?`<label>DNS Subscription اختصاصی</label><div class="copybox"><code>${esc(c.dnsSubscription)}</code><button onclick="copy('${enc(c.dnsSubscription)}')">کپی</button></div><label>DNS اختصاصی DoH</label><div class="copybox"><code>${esc(c.dnsUrl||'')}</code><button onclick="copy('${enc(c.dnsUrl||'')}')">کپی</button></div><div class="callout">DNS اختصاصی پنل · سهمیه ${esc(c.remainingText||'')}</div>`:(c.protocol==='vless'||c.protocol==='vmess'?`<label>Subscription</label><div class="copybox"><code>${esc(c.subscription)}</code><button onclick="copy('${enc(c.subscription)}')">کپی</button></div>`:'<div class="callout">برای این پروتکل Subscription عمومی فعال نیست.</div>')}</div>`).join(''):'<div class="empty">برای نمایش کانفیگ، ابتدا یک کلاینت بسازید.</div>'}
async function createClient(){let name=$('name').value.trim(),gb=+$('gb').value,days=+$('days').value,protocol=$('protocol').value,dnsServer='';if(!name||gb<=0||days<=0)return $('createMsg').textContent='اطلاعات را کامل وارد کنید.';try{let d=await req('/api/clients/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gb,days,protocol,dnsServer})});$('createMsg').textContent='کلاینت ساخته شد.';$('name').value='';await refresh();openTab('configs');setTimeout(()=>copy(protocol==='dns'?d.client.dnsUrl:d.client.subscription),100)}catch(e){$('createMsg').textContent=e.message}}
async function del(id){if(!confirm('این کلاینت حذف شود؟'))return;await req('/api/clients/'+id+'/delete',{method:'POST'});refresh()}
async function loadSettings(){try{let d=await req('/api/settings');settings=d.settings;$('setHost').value=settings.node_host||'';$('setPort').value=settings.node_port||443;$('setPath').value=settings.ws_path||'/ws';$('setVmessPath').value=settings.vmess_path||'/vmess';$('setSub').value=settings.sub_path||'sub';$('setTitle').value=settings.panel_title||'vpnstan';$('setSupport').value=settings.support_url||'';$('setWgEndpoint').value=settings.wg_endpoint||'';$('setWgKey').value=settings.wg_server_public_key||'';updateDash()}catch{}}
async function saveSettings(){try{let d=await req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_host:$('setHost').value,node_port:$('setPort').value,ws_path:$('setPath').value,vmess_path:$('setVmessPath').value,sub_path:$('setSub').value,panel_title:$('setTitle').value,support_url:$('setSupport').value,wg_endpoint:$('setWgEndpoint').value,wg_server_public_key:$('setWgKey').value})});settings=d.settings;$('setMsg').textContent='تنظیمات ذخیره شد.';refresh()}catch(e){$('setMsg').textContent=e.message}}
function updateDash(){$('dashHost').textContent=settings.node_host||'همان دامنه پنل';$('dashPort').textContent=settings.node_port||'443'}
async function logout(){await req('/api/logout',{method:'POST'});location.reload()}
async function copy(s){s=dec(s);try{await navigator.clipboard.writeText(s);alert('کپی شد')}catch{prompt('مقدار:',s)}}
const enc=s=>btoa(unescape(encodeURIComponent(s))),dec=s=>decodeURIComponent(escape(atob(s))),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
(async()=>{try{let d=await req('/api/me');if(d.authenticated)showApp()}catch{}})();

async function changeAccount(){try{let d=await req('/api/account/change',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('accUser').value,oldPassword:$('accOld').value,newPassword:$('accNew').value})});$('accMsg').textContent=d.msg||'ذخیره شد؛ دوباره وارد شوید';setTimeout(()=>location.reload(),1200)}catch(e){$('accMsg').textContent=e.message}}
async function loadUsers(){try{let d=await req('/api/admin/users');$('usersList').innerHTML=d.users.map(u=>`<div class="client-row"><div><b>${esc(u.username)}</b><small>${u.role==='admin'?'ادمین':'کاربر'} · ${u.enabled?'فعال':'غیرفعال'}</small></div><div class="row-actions"><button class="mini" onclick="toggleUser(${u.id})">${u.enabled?'غیرفعال کردن':'فعال کردن'}</button><button class="danger mini" onclick="deleteUser(${u.id})">حذف</button></div></div>`).join('')}catch(e){}}
async function createUser(){try{let d=await req('/api/admin/users/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('newUser').value,password:$('newPass').value,role:$('newRole').value})});$('adminMsg').textContent='اکانت ساخته شد.';$('newUser').value='';$('newPass').value='';loadUsers()}catch(e){$('adminMsg').textContent=e.message}}
async function toggleUser(id){try{await req('/api/admin/users/'+id+'/toggle',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
async function deleteUser(id){if(!confirm('این اکانت حذف شود؟'))return;try{await req('/api/admin/users/'+id+'/delete',{method:'POST'});loadUsers()}catch(e){alert(e.message)}}
