const $=id=>document.getElementById(id);let clients=[],settings={};
async function req(u,o={}){let r=await fetch(u,{credentials:'include',...o});let d=await r.json();if(!r.ok)throw Error(d.msg||'خطا');return d}
function openTab(id){document.querySelectorAll('.tab').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));let t={dashboard:'داشبورد',clients:'کلاینت‌ها',configs:'کانفیگ‌ها و Subscription',settings:'تنظیمات'}[id];$('title').textContent=t;if(id==='configs')renderConfigs()}
document.querySelectorAll('.nav').forEach(x=>x.onclick=()=>openTab(x.dataset.tab));
async function login(){try{let d=await req('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});if(!d.success)throw Error(d.msg);showApp()}catch(e){$('loginMsg').textContent=e.message}}
function showApp(){$('login').classList.add('hidden');$('app').classList.remove('hidden');refresh();loadSettings()}
async function refresh(){try{let d=await req('/api/clients');clients=d.clients;$('count').textContent=clients.length;$('active').textContent=clients.filter(x=>x.enabled&&!expired(x)).length;$('expired').textContent=clients.filter(expired).length;renderClients();renderConfigs();updateDash()}catch(e){if(e.message.includes('ورود'))location.reload()}}
function expired(c){return c.expiryAt && c.expiryAt*1000<Date.now()}
function renderClients(){$('clientsList').innerHTML=clients.length?clients.map(c=>`<div class="client-row"><div><b>${esc(c.name)}</b><small>${c.gb} GB · ${c.days} روز · ${expired(c)?'منقضی':'فعال'}</small></div><div class="row-actions"><button class="mini" onclick="copy('${enc(c.vless)}')">کپی VLESS</button><button class="mini" onclick="copy('${enc(c.subscription)}')">کپی Sub</button><button class="danger mini" onclick="del(${c.id})">حذف</button></div></div>`).join(''):'<div class="empty">هنوز کلاینتی ساخته نشده است.</div>'}
function renderConfigs(){$('configList').innerHTML=clients.length?clients.map(c=>`<div class="config-card"><div class="config-top"><div><b>${esc(c.name)}</b><span class="tag">${expired(c)?'منقضی':'فعال'}</span></div><small>${c.gb} GB · تا ${new Date(c.expiryAt*1000).toLocaleDateString('fa-IR')}</small></div><label>VLESS</label><div class="copybox"><code>${esc(c.vless)}</code><button onclick="copy('${enc(c.vless)}')">کپی</button></div><label>Subscription</label><div class="copybox"><code>${esc(c.subscription)}</code><button onclick="copy('${enc(c.subscription)}')">کپی</button></div></div>`).join(''):'<div class="empty">برای نمایش کانفیگ، ابتدا یک کلاینت بسازید.</div>'}
async function createClient(){let name=$('name').value.trim(),gb=+$('gb').value,days=+$('days').value;if(!name||gb<=0||days<=0)return $('createMsg').textContent='اطلاعات را کامل وارد کنید.';try{let d=await req('/api/clients/create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,gb,days})});$('createMsg').textContent='کلاینت ساخته شد.';$('name').value='';await refresh();openTab('configs');setTimeout(()=>copy(d.client.subscription),100)}catch(e){$('createMsg').textContent=e.message}}
async function del(id){if(!confirm('این کلاینت حذف شود؟'))return;await req('/api/clients/'+id+'/delete',{method:'POST'});refresh()}
async function loadSettings(){try{let d=await req('/api/settings');settings=d.settings;$('setHost').value=settings.node_host||'';$('setPort').value=settings.node_port||443;$('setPath').value=settings.ws_path||'/ws';$('setSub').value=settings.sub_path||'sub';$('setTitle').value=settings.panel_title||'vpnstan';$('setSupport').value=settings.support_url||'';updateDash()}catch{}}
async function saveSettings(){try{let d=await req('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({node_host:$('setHost').value,node_port:$('setPort').value,ws_path:$('setPath').value,sub_path:$('setSub').value,panel_title:$('setTitle').value,support_url:$('setSupport').value})});settings=d.settings;$('setMsg').textContent='تنظیمات ذخیره شد.';refresh()}catch(e){$('setMsg').textContent=e.message}}
function updateDash(){$('dashHost').textContent=settings.node_host||'همان دامنه پنل';$('dashPort').textContent=settings.node_port||'443'}
async function logout(){await req('/api/logout',{method:'POST'});location.reload()}
async function copy(s){s=dec(s);try{await navigator.clipboard.writeText(s);alert('کپی شد')}catch{prompt('مقدار:',s)}}
const enc=s=>btoa(unescape(encodeURIComponent(s))),dec=s=>decodeURIComponent(escape(atob(s))),esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
(async()=>{try{let d=await req('/api/me');if(d.authenticated)showApp()}catch{}})();
